#! /bin/bash

# filename:
# Author: Gerson Lindor Jr.  (lindorg@oregontate.edu)
# Date Created: January 13, 2020
# Last Modified: January 13, 2020



#
main() {
    operations $1
}


#
scriptError() {
ls


}


#
pathFinding() {

ls

}

#
operations() {
    echo -e "param 1 in operations = $1"
    echo -e "param 0 = $0"
    # check argument count
    # check if file is readable
    if [ $1 = "dims" ]
    then
        dims 
    fi
}


# may not use this
stdinOps() {
ls



}


#  may not use this
otherOps() {
ls


}


#
dims() {
    # get rows
    rows=$( cat $datafilepath | wc -l )
    # get columns
    local line=$( head -1 $datafilepath ) # grap the first line
    echo -e "line = $line"
    # count the number of elements in a line to find the number of columns
    for i in $line
    do
        cols=$(( cols + 1 ))
    done
    # final output
    echo -e "$rows $cols"
}


#
transpose () {
ls



}


#### Running the Script ####

datafilepath="datafile$$"
opsName="N/A"
rows=0
cols=0


# handle any errors that effects the script as a whole:
# ./matrix or matrix cannot be the last argument
# the matrix file is readable
# generate path of file via stdin or a file
if [ "$#" = "1" ]
then
    cat > "$datafilepath"
elif [ "$#" = "2" ]
then
    datafilepath=$2
fi

main $1
    


